/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import type { SetFrontEndData } from '../models/system-config';
import { ResponseOneIf } from '../models/common';
import { environment } from 'src/environments/environment';

@Injectable({ providedIn: 'root' })
export class SystemConfigService {
    constructor(private http: HttpClient) {}

    putSetFrontend(id: number, setFrontEndData: SetFrontEndData): Observable<ResponseOneIf<SetFrontEndData>> {
        return this.http.put<ResponseOneIf<SetFrontEndData>>(
            `${environment.apiUrl}/system-config/set-frontend/${id}`,
            setFrontEndData
        );
    }
    getSetFrontend(): Observable<ResponseOneIf<SetFrontEndData>> {
        return this.http.get<ResponseOneIf<SetFrontEndData>>(`${environment.apiUrl}/system-config/set-frontend`);
    }
    
}
